<?php

namespace Application\UserBundle\Entity;

use Doctrine\ORM\EntityRepository;

/**
 * CRInfoRepository
 *
 * This class was generated by the PhpStorm "Php Annotations" Plugin. Add your own custom
 * repository methods below.
 */
class CRInfoRepository extends EntityRepository
{
}
