<?php

namespace Application\UserBundle\Entity;

/**
 * CRStatRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class CRStatRepository extends \Doctrine\ORM\EntityRepository
{
}
